### ISSUE TITLE
Make docs/examples cpu friendly

### ISSUE THREAD

**Issue by mvdoc** [gallantlab/himalaya#27]
The examples require GPU for building. This makes it impossible to automate pushing docs with travis. We need to either skip running the examples that require a GPU, or make all examples use `torch`.

**Comment by TomDLT** [comment]
We could systematically use `set_backend(..., on_error="warn")` in the examples, which warns instead of erroring when the backend is not available.
I wonder how long would the build take without GPU though.

**Comment by TomDLT** [comment]
Fixed in 617c35c6489af262d6feac716fc15d8d23621d62
